### ISSUE TITLE
Empty connections array

### ISSUE THREAD

**Issue by eslamoo** [nitinsurana/jsPlumb-Persistence#2]
Thank you for this amazing work,
i dont know if this plugin still supported or not.
but i have an issue when save the json the object returns with only the blocks, and the connections array empty. any advise?

**Comment by eslamoo** [comment]
@nitinsurana is this plugin still supported?

**Comment by nitinsurana** [comment]
@eslamoo This plugin is very old and a lot has changed since then in JsPlumb.
It is no wonder why connections array is empty.
PRs are welcome. 
I'll spend some time over the coming weekend to see if it can be made compatible with latest jsPlumb release.

Meanwhile, I've updated the demos link in the readme.

Demo - http://nitinsurana.github.io/jsPlumb-Persistence/

**Comment by eslamoo** [comment]
@nitinsurana I can't find anything strange in the plugin. Everything is normal, and I am surprised that it does not work. So I decided to show you my code so that you might find any conflicts, incompatible names that are causing this problem, [check this](https://paiza.io/projects/e/QPyupQ2l-8wYO7Y0ApB1lg?theme=twilight)
 because I am sure there have been no changes in the jsPlumb,  especially since I tried this code and it works well:
`

        $('#save').on('click', function() {
          

          var nodes = []

          $(".workplace .node").each(function (idx, elem) {
            var $elem = $(elem);
            var endpoints = instance.getEndpoints($elem.attr('id'));
            nodes.push({
              id: $elem.attr('id'),
              html: $elem[0].outerHTML,
              positionX: parseInt($elem.css("left"), 10),
              positionY: parseInt($elem.css("top"), 10)
            });

          });
          var connections = [];
          $.each(instance.getAllConnections(), function (idx, connection) {


            connections.push({
              connectionId: connection.id,
              sourceId: connection.sourceId,
              targetId: connection.targetId,
              sourceEndpointUuid: connection.endpoints[0].getUuid(),
              targetEndpointUuid: connection.endpoints[1].getUuid(),

              anchors: $.map(connection.endpoints, function (endpoint) {

                return [
                  [endpoint.anchor.x,
                    endpoint.anchor.y,
                    endpoint.anchor.orientation[0],
                    endpoint.anchor.orientation[1],
                    endpoint.anchor.offsets[0],
                    endpoint.anchor.offsets[1]
                  ]
                ];

              })
            });
          });

          var flowChart = {};
          flowChart.nodes = nodes;
          flowChart.connections = connections;
          console.log(JSON.stringify(flowChart));
          
        });`
 As you can see, there is no difference between it and your code and its log the connections as well, but I want to use your plugin in order to benefit from the load function as well.
Thanks in advance

**Comment by eslamoo** [comment]
#3

**Comment by eslamoo** [comment]
#3 @nitinsurana Please check this pull request, i solved connections empty array issue but there is another problem now after load the chart from the saved json the connections appears in wrong places and the endpoints are hidden, you can check the live preview from this [link](https://serene-snyder-b4a4a2.netlify.app/#/try) and the [repo](https://github.com/eslamoo/glocom) as well, looking forward for your help.

**Comment by nitinsurana** [comment]
I checked the original [demo](http://nitinsurana.github.io/jsPlumb-Persistence/demos.html) and it's working as expected.

"Save" saves a diagram with it's state/position and creates json
"Delete" deletes the diagram container
"Load" loads the json present in the text area. And it looks exactly the way it was saved i.e. changes to the diagram are evident upon  loading back.

**Comment by nitinsurana** [comment]
Thanks for creating this - https://serene-snyder-b4a4a2.netlify.app/#/try
After looking at it, I guess we'll need to save more information in order to reconstruct the graph.
Don't have a definite answer as of now on what all do we need.

The `load` loads a previously saved graph fetched from an API.
Can you amend the example to load what we just saved.

**Comment by nitinsurana** [comment]
I think I know the root-cause why the connections aren't tied to the correct object.

Your code
<img width="542" alt="your_code" src="https://user-images.githubusercontent.com/7137160/85938288-b483f580-b8c0-11ea-9f28-cc09420a8406.png">

Plugin
<img width="600" alt="plugin" src="https://user-images.githubusercontent.com/7137160/85938289-b64db900-b8c0-11ea-9cd6-91ed5ead637b.png">

It doesn't appear you're using the plugin; or probably made a mistake while copying the code.

Due to above html extraction code change, another node within is created with the same id upon loading and hence, the connections go awry.
<img width="512" alt="Screenshot 2020-06-27 at 22 01 52" src="https://user-images.githubusercontent.com/7137160/85938386-d6ca4300-b8c1-11ea-9a63-bbfce970b24f.png">

**Comment by nitinsurana** [comment]
Regarding the anchors not getting created after loading:

They are not saved, atleast not along side node.

Solution:
1. After loading the graph, iterate over the nodes and manually add the anchors.
2. Another solution could be to tweak the node re-construction code in `load` method and add anchors there.
3. Of course, the long solution is to fetch & save anchor information associated with every node. In which case, the graph reconstruction order would be
* create node
* create anchors attached to this node
* create connections

**Comment by eslamoo** [comment]
You are right, I have modified this part and the connections work well now in their specific locations, however I did what you said regarding the endpoints and added it manually after load the graph but its not draggable as you can see in this [link](https://serene-snyder-b4a4a2.netlify.app/#/try) this is the last point in the problems list, working code in `views/try.vue` and the json is static in `static/data.json` do you have any idea how to make endpoints draggable with its own node like normal behvior?

**Comment by eslamoo** [comment]
When you need to update the json just copy what logged in the console and paste it in the `data.json` because its the library test stage before include it the main project and integrate with API, now just trying to make things work, but i wonder why when i re-save the graph after load it the connections array be empty i must redraw them to make jsPlumb see them

**Comment by nitinsurana** [comment]
If I understand the problem correctly, then after loading the saved json data, the nodes are draggable but the anchors gets de-attached when the parent node starts dragging.

<img width="943" alt="Screenshot 2020-06-28 at 14 20 01" src="https://user-images.githubusercontent.com/7137160/85958454-76331880-b94a-11ea-8bb8-35a3aff9739f.png">

**Comment by nitinsurana** [comment]
For some weird reason, if I try editing the code inside try.vue in Chrome Developer Tools, it still runs the old code.
Can you try two things:
1. Use `jsPlumb.addEndpoint` instead of `instance.addEnpoint`
2. If I understand the [addEndpint api](https://docs.jsplumbtoolkit.com/community/current/articles/connections.html) correctly, 
```
let s0 = instance.addEndpoint(toId, sourceEndpoint, {
              anchor: sourceAnchors[i],
              uuid: sourceUUID,
            });
```
should be changed to
```
let s0 = instance.addEndpoint(toId, {
              anchor: sourceAnchors[i],
              uuid: sourceUUID,
            },sourceEndpoint);
```

**Comment by eslamoo** [comment]
Wow its working, you have been extremely supportive through this difficult time. I could not have gotten through it without you, Thank you man, but there is one more thing i cant even understand, why the connections that loaded from the json cannot be saved one more time and when i remove a node the connection still appears and i guess these two problems are related to each other, one solution will solve the two issues i updated the code as well you can clear the cache and take a quick look, just click the save button after the load button and see the logged data you will find the connections array empty

**Comment by eslamoo** [comment]
I realize that the `instance.getAllConnections()` doesn't work with loaded data but `jsPlumb.getAllConnections()`does so now i should create a new save function with same code and just change the `instance` to `jsPlumb` is this make sense or is the this best practice?

**Comment by eslamoo** [comment]
If you try to drag new node from the left side after load the data and try to connect it to the loaded nodes it won't be connected do you know why?

**Comment by eslamoo** [comment]
now i replaced all `instance` in the project to `jsPlumb` and everything is fine now. Thanks a lot.

**Comment by eslamoo** [comment]
Thanks a lot man I wish I have your linkedin account or personal email so we can work together in future projects essomgd@gmail.com :)
